### ISSUE TITLE
crash on start pls help can somebody give me a solution? ps when I restart the app it works just fine

### ISSUE THREAD

**Issue by Bazixv13** [szkolny-eu/szkolny-android#183]
this is the error message: 

Build version: 4.13.6 
Build date: 1981-01-01 01:01:02 
Current date: 2023-09-12 10:24:22 
Device: Xiaomi M2101K7BNY 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service pl.szczodrzynski.edziennik/.data.api.ApiService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4775)
	at android.os.Parcel.readParcelable(Parcel.java:4743)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6039)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1904)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1880)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
	at pl.szczodrzynski.edziennik.data.api.task.c$a.a(IApiTask.kt:4)
	at pl.szczodrzynski.edziennik.data.firebase.d.<init>(SzkolnyLibrusFirebase.kt:57)
	at pl.szczodrzynski.edziennik.data.firebase.MyFirebaseService$c.k(MyFirebaseService.kt:14)
	at z9.a.f(ContinuationImpl.kt:4)
	at kotlinx.coroutines.r0.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.a.g0(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.d(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.n(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)

User actions: 
2023-09-12 09:33:36: MainActivity created
2023-09-12 09:33:36: MainActivity resumed
2023-09-12 09:33:45: MainActivity paused
2023-09-12 09:38:51: MainActivity resumed
2023-09-12 09:38:54: MainActivity paused
2023-09-12 09:38:55: MainActivity destroyed
2023-09-12 09:38:55: MainActivity created
2023-09-12 09:38:55: MainActivity resumed
2023-09-12 09:38:59: MainActivity paused
2023-09-12 09:38:59: MainActivity resumed
2023-09-12 09:39:01: MainActivity paused
2023-09-12 09:47:59: MainActivity resumed
2023-09-12 09:48:29: MainActivity paused
2023-09-12 09:48:29: MainActivity resumed
2023-09-12 09:48:31: MainActivity paused
2023-09-12 10:20:16: MainActivity resumed
2023-09-12 10:20:20: MainActivity paused

**Comment by kuba2k2** [comment]
Please wipe app data and login again, it will work. Probably something got corrupted in the database.

**Comment by cki-gh-rafal-wanke** [comment]
@kuba2k2 unfortunately wiping data, reinstalling doesn't work, after some time it still crashes, no notification thou

`Build version: 4.13.6 
Build date: 1981-01-01 01:01:02 
Current date: 2023-10-13 09:03:57 
Device: Samsung SM-S911B 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service pl.szczodrzynski.edziennik/.data.api.ApiService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
	at android.os.Parcel.readParcelable(Parcel.java:4755)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6214)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1967)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at pl.szczodrzynski.edziennik.data.api.task.c$a.a(IApiTask.kt:4)
	at pl.szczodrzynski.edziennik.data.firebase.d.<init>(SzkolnyLibrusFirebase.kt:57)
	at pl.szczodrzynski.edziennik.data.firebase.MyFirebaseService$c.k(MyFirebaseService.kt:14)
	at z9.a.f(ContinuationImpl.kt:4)
	at kotlinx.coroutines.r0.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.a.g0(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.d(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.n(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)

User actions: 
`
